### ISSUE TITLE
多条件问题

### ISSUE THREAD

**Issue by JeremieCHN** [xjdrew/lua-zset#12]
### 问题描述
我们项目基于zset来做排行榜，我们的排行榜的基础设计是：以一个分数来排序，同分情况下，先上榜的人在前。但是zset只支持一个条件。
### 现行方案及其问题
我们的现行方案就是直接前面32位放分数，后面32位放一个0xFFFFFFFF-时间戳。结果数值膨胀，分数放不下了。
### 改进方案
1. slInsert中去掉了compObj的条件，这样一来，同分不按照字典序，而是先上榜的自然放在了前面。限制是这样只能用于降序的榜（即最高分第一名）
2. 直接去掉c层的score，从lua层传一个比较用的function下来，这样灵活性拉满，但是太灵活了，对于原来skiplist的实现有很大的侵入，而且要是比较用的function里有个网络调用、或者相同输入不同返回值、或者比较不满足传递闭包就炸了
3. 把score从一个double改成一个double列表，这种能满足很多需求，唯一的限制是必须各种条件都转成number，并且必须同向（不能A条件是越大越好，B条件是越小越好，但是这可以通过找个最大值减去B来转化）
### 我的问题
几个改进方案各有优劣，想问问看作者的想法。

**Comment by hanxi** [comment]
方案 3 比方案 2 适合一些吧，lua 层把接口封装好的话，一样能灵活。方案 3 我好像写过一次。

**Comment by hanxi** [comment]
我记错了，我实现的是支持 cmp 函数，以及把 score 改成字符串了。

**Comment by hanxi** [comment]
代码贴在这里 https://gist.github.com/hanxi/96094b32b5713f21affc7d12676b554a

之前是给 LPC 用的，所以没有 Lua 代码。

**Comment by JeremieCHN** [comment]
我自己也实现了方案2和方案3，不过现在项目上不管2还是3都用不了，涉及到的修改太多了。下个项目应该是用方案3来处理了。

**Comment by xjdrew** [comment]
把member改成`产生分数的时间戳+member` ，这样member会优先遵守时间顺序；
在lua层除了记录member -> score关系，也记录一下member -> 产生分数的时间戳关系；

别的逻辑稍微转换一下就好了。
不知道这样能不能满足需要。

**Comment by JeremieCHN** [comment]
我们已经直接用方案1解决当前问题了，前面说的，项目这个阶段了，不好修改了，其他方案都需要去改数据。

我主要是想探讨一下多条件的方案，目前我们总是把多个条件塞进一个64位的score里，结果光时间戳就用掉了32位，局限性太明显了。
改动member我完全没想过，能满足我们的需要，和你说的一样，“别的逻辑稍微转换一下就好了”，而且64位里面现在全部用来放时间以外的条件，已经能完全覆盖项目的需求了。

非常感谢两位的回复！
